export const notes = [
  {
    id: "1",
    headline: "Light Preference",
    note: "Prefers indirect sunlight, keep away from direct afternoon sun",
    noteLocation: "1",
    dateCreated: "26.10.2024",
  },
  {
    id: "2",
    headline: "Watering Instructions",
    note: "Water only when the topsoil feels dry, avoid overwatering",
    noteLocation: "2",
    dateCreated: "26.10.2024",
  },
  {
    id: "3",
    headline: "Temperature Tolerance",
    note: "Keep in a temperature range of 18-25°C for optimal growth",
    noteLocation: "3",
    dateCreated: "26.10.2024",
  },
  {
    id: "4",
    headline: "Fertilizing Guide",
    note: "Use a balanced liquid fertilizer every 4 weeks during spring and summer",
    noteLocation: "4",
    dateCreated: "26.10.2024",
  },
  {
    id: "5",
    headline: "Pruning Tips",
    note: "Prune dead or yellowing leaves to encourage new growth",
    noteLocation: "5",
    dateCreated: "26.10.2024",
  },
  {
    id: "6",
    headline: "Repotting Advice",
    note: "Repot every 1-2 years using fresh potting mix",
    noteLocation: "6",
    dateCreated: "26.10.2024",
  },
  {
    id: "7",
    headline: "Humidity Needs",
    note: "Prefers moderate humidity, consider misting in dry environments",
    noteLocation: "7",
    dateCreated: "26.10.2024",
  },
  {
    id: "8",
    headline: "Pest Prevention",
    note: "Inspect leaves regularly for pests like spider mites or aphids",
    noteLocation: "8",
    dateCreated: "26.10.2024",
  },
  {
    id: "9",
    headline: "Growth Rate",
    note: "Slow to moderate grower, depending on light and watering conditions",
    noteLocation: "9",
    dateCreated: "26.10.2024",
  },
  {
    id: "10",
    headline: "Soil Requirements",
    note: "Use well-draining soil to prevent root rot",
    noteLocation: "10",
    dateCreated: "26.10.2024",
  },
  {
    id: "11",
    headline: "Toxicity Warning",
    note: "Toxic to pets if ingested, keep out of reach of animals",
    noteLocation: "11",
    dateCreated: "26.10.2024",
  },
  {
    id: "12",
    headline: "Propagation Method",
    note: "Can be propagated through stem cuttings in water or soil",
    noteLocation: "12",
    dateCreated: "26.10.2024",
  },
  {
    id: "13",
    headline: "Flowering Information",
    note: "Rarely flowers indoors, blooms are small and inconspicuous",
    noteLocation: "13",
    dateCreated: "26.10.2024",
  },
  {
    id: "14",
    headline: "Light Adjustment",
    note: "Rotate the pot weekly to ensure even light exposure",
    noteLocation: "14",
    dateCreated: "26.10.2024",
  },
  {
    id: "15",
    headline: "Seasonal Care",
    note: "Reduce watering during the winter months",
    noteLocation: "15",
    dateCreated: "26.10.2024",
  },
];
